bf16: true
cutoff_len: 1500
dataset: mydataset
ddp_timeout: 180000000
do_train: true
eval_steps: 500
eval_strategy: steps
finetuning_type: lora
gradient_accumulation_steps: 8
learning_rate: 0.0001
logging_steps: 10
lora_target: all
lr_scheduler_type: cosine
max_samples: 1000
model_name_or_path: ./pre-trained/qwen/Qwen2-7B-Instruct
num_train_epochs: 3.0
output_dir: ./output/qwen2_lora_sft_v4_chechpoint
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
save_steps: 56
stage: sft
template: qwen
val_size: 0.1
warmup_ratio: 0.1
